---
title: "Fake News"
output:
  html_document:
    df_print: paged
---



```{r}
## Libraries
library(tidyverse)
library(sentimentr)
library(ngram)

## Read in the Data
fakeNews.train <- read_csv("train.csv")
fakeNews.test <- read_csv("test.csv")
fakeNews <- bind_rows(train=fakeNews.train, test=fakeNews.test,
                      .id="Set")

fakeNews$text <- tolower(fakeNews$text)
fakeNews$author <- tolower(fakeNews$author)
```


```{r}
# before storing label as a factor
# counts number of fake news authors
(fake <- fakeNews %>%
  filter(label == 1) %>%
  group_by(author) %>%
  summarise(n = sum(label)) %>%
  arrange(-n)) %>% head

# counts number of real news authors
(legit <- fakeNews %>%
  filter(label == 0) %>%
  group_by(author) %>%
  summarise(n = sum(label + 1)) %>%
  arrange(-n)) %>% head

sum( fake$author %in% legit$author) #calculates number of overlap between the two lists

#labels safe authors as "reliable" and fake news authors with "unreliable"
fakeNews$author <- ifelse(fakeNews$author %in% fake$author, "unreliable", "reliable")
```

```{r}
fakeNews$label <- as.factor(fakeNews$label)
ggplot(data = fakeNews %>% filter(label == c(0,1)), mapping = aes(x=label)) + geom_bar() + theme_classic()
```



```{r}
fakeNews$lan_text <- cld2::detect_language(text = fakeNews$text, plain_text = FALSE)

fakeNews$lan_title <- cld2::detect_language(text = fakeNews$title, plain_text = FALSE)

unique(fakeNews$lan_text)
sum(fakeNews$lan_text != fakeNews$lan_title, na.rm = TRUE)
```

```{r}
#strip punctuation, return number of characters, word count, more to add
strip <- function(x){
  stripped <- str_replace_all(x, "[[:punct:]]", "")
  mywords <- wordcount(stripped)
  return(mywords)
}
fakeNews <- fakeNews %>%
  mutate(wcount = map_int(text,strip))
```


```{r}
token_obj <- quanteda::tokens(fakeNews$text, remove_numbers = FALSE, remove_punct = FALSE, remove_symbols = TRUE, remove_separators = TRUE)

lex_div <- quanteda::textstat_lexdiv(token_obj, measure = c("TTR", "C", "R", "CTTR"))

fakeNews$lex_div <- lex_div$TTR
```


```{r}
fakeNews$lex_div <- lex_div$TTR
ggplot(fakeNews %>% filter(label == c(0,1)), mapping = aes(x = label, y = lex_div)) + geom_boxplot() + theme_classic()


```


```{r}
#sentiment_df <- sentiment_by(get_sentences(fakeNews$text))
#fakeNews$tone <- sentiment_df$ave_sentiment
```

